export const TILE_WIDTH_CELLS = 32
export const TILE_HEIGHT_CELLS = 32

export const DEFAULT_ATLAS_SIZE = 2048
export const MAX_ATLAS_PAGES = 3

export const MAX_GLYPH_UPLOADS_PER_FRAME = 16

export const SCROLL_TEXTURE_FILTER = 0x2600 // NEAREST

export const CONTENT_TEXTURE_INTERNAL_FORMAT = 0x8058 // RGBA8
export const CONTENT_TEXTURE_FORMAT = 0x1908 // RGBA
export const CONTENT_TEXTURE_TYPE = 0x1401 // UNSIGNED_BYTE

export const ATLAS_TEXTURE_INTERNAL_FORMAT = 0x8058 // RGBA8
export const ATLAS_TEXTURE_FORMAT = 0x1908 // RGBA
export const ATLAS_TEXTURE_TYPE = 0x1401 // UNSIGNED_BYTE
